    - name: Install Python
      apt: name={{ item }} state=present
      loop:
       - python3.10
       - python3.10-dev
       - python3.10-venv

    - name: Remove Pexpect Conflicts
      apt: name={{ item }} state=absent
      loop:
        - python-pexpect
        - python3-pexpect